store:
  entities:
    - label: "Data Store"
      type: "es_vec"
      parameters:
        host_name: "es"
        image_index_name: "image"
        text_index_name: "text"
        video_index_name: "video"
        audio_index_name: "audio"

operators:
  label: "Operators"
  parameters:
    - name: "Video Vector Representation"
      type: "vid_vec_rep_clip"
      parameters: { index_name: "video" }