[project]
name = "feluda-dimension-reduction"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = ["scikit-learn>=1.5.1", "numpy>=2.0.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.semantic_release]
version_variable = ["pyproject.toml:project.version"]

[tool.semantic_release.branches.main]
match = "main"
prerelease = false
tag_format = "{name}-{version}"

[tool.hatch.build.targets.wheel]
packages = ["."]
