#wget "https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.vec.gz"
#wget "https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.hi.300.vec.gz"
#wget "https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.gu.300.vec.gz"
wget "https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/wiki.ta.align.vec"
wget "https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/wiki.bn.align.vec"
wget "https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/wiki.en.align.vec"
wget "https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/wiki.hi.align.vec"
