#################### CONFIG INDEXER #################### 
# This configuration file defines components needed to run the indexer.py. 
# The indexer will receive a media file while listening to the index queue, run operations on it, store it in elasticsearch and report to the report queue

store :
  label : "Data Store"
  type : "es_vec"
  parameters:
    host_name : "es"
    image_index_name : "image"
    text_index_name : "text"
    video_index_name : "video"
    audio_index_name : "audio"

queue : 
  label : "Queue"
  type : "rabbitmq"
  parameters: 
    host_name : "rabbitmq"
    queues:
      - name : "tattle-search-index-queue"
      - name : "tattle-search-report-queue"

operators : 
  label : "Operators"
  parameters :
    - name : "Video Vector Representation"
      type : "vid_vec_rep_resnet"
      parameters: {
        index_name : "video"
      }
