### TEST IMAGE ###
FROM --platform=$TARGETPLATFORM python:3.11-slim-bullseye@sha256:47863f26a5f2e0bfa903e7b658355940250979bd555b5e4f9f25da81647daff8 AS test
ARG UID
ARG GID

# Update image, install required utils, and remove cache
RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get install -y --no-install-recommends vim zsh curl wget grep \
    && rm -rf /var/lib/apt/lists/*

# Set python group and user, create home dir, create app dir, change ownership of app to user
RUN groupadd -g $GID python \
    && useradd --create-home -r -u $UID -g python python \
    && mkdir /home/python/app \
    && chown -R python:python /home/python/app/

# Set working dir
WORKDIR /home/python/app

# Create venv and change ownership recursively
RUN python -m venv /home/python/app/venv \
    && chown -R python:python /home/python/app/venv
# Set venv in path
ENV PATH="/home/python/app/venv/bin:$PATH"

# Copy base, core and operator requirements
COPY --chown=python:python base_requirements.txt /home/python/app/base_requirements.txt
COPY --chown=python:python requirements.txt /home/python/app/requirements.txt
COPY --chown=python:python ./core/operators/vid_vec_rep_resnet_requirements.txt /home/python/app/core/operators/vid_vec_rep_resnet_requirements.txt
COPY --chown=python:python ./core/operators/audio_vec_embedding_requirements.txt /home/python/app/core/operators/audio_vec_embedding_requirements.txt

# Run pip install
RUN pip install --no-cache-dir --require-hashes --no-deps -r /home/python/app/base_requirements.txt \
    && pip install --no-cache-dir --require-hashes --no-deps -r /home/python/app/requirements.txt \
    && pip install --no-cache-dir --require-hashes --no-deps -r /home/python/app/core/operators/vid_vec_rep_resnet_requirements.txt \
    && pip install --no-cache-dir --require-hashes --no-deps -r /home/python/app/core/operators/audio_vec_embedding_requirements.txt

# Copy all files and change ownership to unprivileged user
COPY --chown=python:python . /home/python/app

# Set unprivileged user with group membership
USER python:python

#################################
