name: Publish Hash Worker to Dockerhub for Staging

permissions:
  contents: read

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # v3.2.0

      - name: Login to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v.3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push amd64
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: "{{defaultContext}}:src/"
          file: worker/hash/Dockerfile.hash_worker
          platforms: linux/amd64
          build-args: |
            "UID=1000"
            "GID=1000"
          push: true
          tags: tattletech/feluda-operator-hash:worker-amd64-latest

      - name: Build and push arm64
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: "{{defaultContext}}:src/"
          file: worker/hash/Dockerfile.hash_worker_graviton
          platforms: linux/arm64
          build-args: |
            "UID=1000"
            "GID=1000"
          push: true
          tags: tattletech/feluda-operator-hash:worker-arm64-latest
